// Copyright 2019 David J. Pearce
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package jmodelgen.tests;

import jmodelgen.core.Domain;
import jmodelgen.core.Domains;

public class TestDomains {
	/**
	 * A moderate selection of integers
	 */
	public static Domain.Small<Integer> INTS = Domains.Int(-10, 10);

	/**
	 * A moderate selection of words (7936 to be exact)
	 */
	public static Domain.Small<String> WORDS = Domains.Finite("Source", "Files", "c", "source", "files", "Whiley",
			"programs", "are", "split", "across", "one", "or", "more", "source", "files", "which", "are", "compiled",
			"into", "wyil", "files", "prior", "to", "execution", "source", "files", "contain", "declarations", "which",
			"describe", "the", "functions", "methods", "data", "types", "and", "constants", "which", "form", "the",
			"program", "source", "files", "are", "grouped", "together", "into", "coherent", "units", "called",
			"packages", "Compilation", "Units", "c", "source", "files", "compilation", "units", "Two", "kinds", "of",
			"compilation", "unit", "are", "taken", "into", "consideration", "when", "compiling", "a", "Whiley",
			"source", "file", "other", "source", "files", "and", "binary", "wyil", "files", "The", "Whiley",
			"Intermediate", "Language", "WyIL", "file", "format", "is", "described", "elsewhere", "but", "defines", "a",
			"binary", "representation", "of", "a", "Whiley", "source", "file", "syntax", "SourceFile", "PackageDecl",
			"ImportDecl", "Modifier", "TypeDecl", "Modifier", "StaticVarDecl", "Modifier", "FunctionDecl", "Modifier",
			"MethodDecl", "syntax", "When", "one", "or", "more", "Whiley", "source", "files", "are", "compiled",
			"together", "a", "compilation", "group", "is", "formed", "External", "symbols", "encountered", "during",
			"compilation", "are", "first", "resolved", "from", "the", "compilation", "group", "and", "then", "from",
			"previously", "compiled", "wyil", "files", "Packages", "c", "source", "files", "packages", "Programs", "in",
			"Whiley", "are", "organised", "into", "packages", "to", "help", "reduce", "name", "conflicts", "and",
			"provide", "some", "grouping", "of", "related", "concepts", "A", "Whiley", "source", "file", "may",
			"provide", "an", "optional", "package", "declaration", "to", "identify", "the", "package", "it", "belongs",
			"to", "This", "declaration", "must", "occur", "at", "the", "beginning", "of", "the", "source", "file",
			"syntax", "PackageDecl", "package", "Ident", "Ident", "syntax", "Any", "source", "file", "which", "does",
			"not", "provide", "a", "package", "declaration", "is", "considered", "to", "be", "in", "the", "default",
			"package", "Names", "c", "source", "files", "names", "There", "are", "four", "functional", "entities",
			"which", "can", "be", "defined", "within", "a", "Whiley", "source", "file", "type", "declarations", "c",
			"source", "files", "type", "decl", "constant", "declarations", "c", "source", "files", "constant", "decl",
			"function", "declarations", "c", "source", "files", "function", "decl", "and", "method", "declarations",
			"c", "source", "files", "method", "decl", "These", "define", "named", "entities", "which", "may", "be",
			"referenced", "from", "other", "compilation", "units", "Every", "named", "entity", "has", "a", "unique",
			"fully", "qualified", "name", "constructed", "from", "the", "enclosing", "package", "name", "the", "source",
			"file", "name", "and", "the", "declared", "name", "For", "example", "Graphics", "whiley", "examples", "ch3",
			"eg", "1", "whiley", "This", "declares", "two", "entities", "g2d", "Graphics", "Point", "and", "g2d",
			"Graphics", "Origin", "Two", "named", "entities", "may", "clash", "if", "they", "have", "the", "same",
			"fully", "qualified", "name", "and", "are", "in", "the", "same", "category", "There", "are", "three",
			"entity", "categories", "types", "constants", "and", "functions", "methods", "The", "following",
			"illustrates", "a", "common", "pattern", "examples", "ch3", "eg", "2", "whiley", "Here", "two", "named",
			"entities", "share", "the", "same", "fully", "qualified", "named", "This", "is", "permitted", "because",
			"they", "are", "in", "different", "categories", "Two", "named", "entities", "in", "the", "same", "category",
			"with", "different", "types", "are", "permitted", "in", "some", "circumstances", "and", "this", "is",
			"referred", "to", "as", "overloading", "Currently", "overloading", "is", "only", "supported", "for",
			"entities", "representing", "function", "and", "methods", "or", "function", "and", "method", "types",
			"Imports", "When", "performing", "name", "resolution", "the", "Whiley", "compiler", "first", "attempts",
			"to", "resolve", "names", "within", "the", "same", "source", "file", "For", "any", "remaining",
			"unresolved", "the", "compiler", "examines", "imported", "entities", "in", "reverse", "declaration",
			"order", "Entities", "are", "imported", "using", "an", "import", "declaration", "syntax", "ImportDecl",
			"import", "FromSpec", "Ident", "Ident", "FromSpec", "Ident", "from", "syntax", "A", "declaration", "of",
			"the", "form", "import", "a", "pkg", "File", "imports", "the", "compilation", "unit", "File", "in",
			"package", "a", "pkg", "Named", "entities", "e", "g", "Entity", "within", "that", "compilation", "unit",
			"can", "then", "be", "referenced", "using", "a", "partially", "qualified", "name", "which", "omits", "the",
			"package", "component", "e", "g", "File", "Entity", "A", "declaration", "of", "the", "form", "import",
			"Entity", "from", "a", "pkg", "File", "imports", "the", "named", "entity", "Entity", "from", "the",
			"compilation", "unit", "File", "residing", "in", "package", "a", "pkg", "Note", "this", "does", "not",
			"import", "the", "compilation", "unit", "a", "pkg", "File", "and", "hence", "does", "not", "subsume", "the",
			"statement", "import", "a", "pkg", "File", "A", "wildcard", "may", "be", "used", "in", "place", "of", "the",
			"compilation", "unit", "name", "to", "import", "all", "compilation", "units", "within", "the", "given",
			"package", "e", "g", "import", "some", "pkg", "A", "wildcard", "may", "be", "used", "in", "place", "of",
			"the", "entity", "name", "e", "g", "import", "from", "some", "pkg", "File", "to", "import", "all", "named",
			"entities", "within", "the", "given", "compilation", "unit", "Declarations", "A", "declaration", "defines",
			"a", "new", "entity", "within", "a", "Whiley", "source", "file", "and", "provides", "a", "name", "by",
			"which", "it", "can", "be", "referred", "to", "within", "this", "source", "file", "or", "from", "other",
			"source", "files", "Access", "Control", "Several", "mechanisms", "for", "access", "control", "are",
			"provided", "through", "declaration", "modifier", "syntax", "Modifier", "public", "private", "native",
			"export", "final", "syntax", "itemize", "The", "public", "modifier", "declares", "that", "the",
			"declaration", "is", "visible", "from", "other", "Whiley", "source", "files", "The", "private", "modifier",
			"declares", "that", "the", "declaration", "is", "visible", "only", "within", "the", "enclosing", "Whiley",
			"source", "file", "The", "native", "modifier", "declares", "that", "the", "declaration", "is", "provided",
			"by", "the", "underlying", "system", "The", "export", "modifier", "declares", "that", "the", "declaration",
			"is", "visible", "to", "source", "files", "written", "in", "other", "languages", "Declarations", "with",
			"this", "modifier", "cannot", "be", "overloaded", "The", "final", "modifier", "declares", "that", "the",
			"declaration", "cannot", "be", "reassigned", "itemize", "When", "no", "modifier", "is", "given", "the",
			"default", "of", "private", "is", "assumed", "Notes", "The", "native", "and", "export", "modifiers",
			"together", "form", "the", "ffi", "The", "restriction", "on", "declarations", "declared", "with", "the",
			"export", "modifier", "is", "to", "enable", "names", "to", "be", "exported", "without", "name", "mangling",
			"Type", "Declarations", "c", "source", "files", "type", "decl", "A", "type", "declaration", "declares", "a",
			"named", "type", "within", "a", "Whiley", "source", "file", "The", "declaration", "may", "refer", "to",
			"named", "types", "in", "this", "or", "other", "source", "files", "and", "may", "also", "recursively",
			"refer", "to", "itself", "either", "directly", "or", "indirectly", "syntax", "TypeDecl", "type", "Ident",
			"is", "Type", "Variable", "where", "Expr", "Variable", "Type", "Ident", "syntax", "The", "optional",
			"where", "clause", "defines", "a", "boolean", "expression", "which", "holds", "for", "any", "instance",
			"of", "this", "type", "This", "is", "often", "referred", "to", "as", "the", "type", "invariant", "or",
			"constraint", "which", "ranges", "over", "the", "declared", "variable", "if", "provided", "Examples",
			"Some", "simple", "examples", "illustrating", "type", "declarations", "are", "examples", "ch3", "eg", "3",
			"whiley", "The", "first", "declaration", "defines", "an", "unconstrained", "record", "type", "named",
			"Point", "whilst", "the", "second", "defines", "a", "constrained", "integer", "type", "nat", "Notes", "A",
			"convention", "is", "that", "type", "declarations", "for", "records", "or", "unions", "of", "records",
			"begin", "with", "an", "upper", "case", "character", "e", "g", "Point", "above", "All", "other", "type",
			"declarations", "begin", "with", "lower", "case", "This", "reflects", "the", "fact", "that", "records",
			"are", "most", "commonly", "used", "to", "describe", "objects", "in", "the", "domain", "All", "types",
			"are", "also", "required", "to", "be", "contractive", "This", "means", "for", "example", "that", "the",
			"declaration", "type", "X", "is", "X", "is", "considered", "invalid", "Static", "Variable", "Declarations",
			"c", "source", "files", "constant", "decl", "A", "static", "variable", "declaration", "declares", "a",
			"top", "level", "variable", "within", "a", "Whiley", "source", "file", "with", "an", "optional",
			"initialiser", "expression", "syntax", "StaticVarDecl", "Type", "Ident", "Expr", "syntax", "The", "given",
			"initialiser", "expression", "may", "not", "directly", "or", "indirectly", "refer", "to", "itself", "and",
			"may", "only", "be", "omitted", "in", "conjunction", "with", "the", "native", "modifier", "Initialiser",
			"expressions", "are", "also", "pure", "and", "may", "not", "have", "side", "effect", "i", "e", "invoke",
			"methods", "or", "allocate", "on", "the", "heap", "Examples", "Some", "simple", "examples", "to",
			"illustrate", "static", "variable", "declarations", "are", "examples", "ch3", "eg", "4", "whiley", "The",
			"first", "declaration", "defines", "the", "constant", "TEN", "to", "have", "the", "int", "value", "10",
			"The", "second", "declaration", "defines", "a", "global", "variable", "initialised", "with", "the",
			"constant", "Notes", "Since", "initialiser", "expressions", "across", "a", "compilation", "group", "form",
			"a", "directed", "acyclic", "graph", "static", "variables", "can", "always", "be", "safely", "initialised",
			"Function", "Declarations", "c", "source", "files", "function", "decl", "A", "function", "declaration",
			"defines", "a", "function", "within", "a", "Whiley", "source", "file", "Functions", "are", "pure", "and",
			"may", "not", "have", "side", "effect", "This", "means", "they", "are", "guaranteed", "to", "return", "the",
			"same", "result", "given", "the", "same", "arguments", "and", "are", "permitted", "within",
			"specifications", "i", "e", "in", "type", "invariants", "loop", "invariants", "and", "function", "method",
			"preconditions", "or", "postconditions", "Functions", "may", "call", "other", "functions", "but", "may",
			"not", "call", "other", "methods", "Functions", "may", "not", "explicitly", "allocate", "memory", "on",
			"the", "heap", "and", "or", "instigate", "concurrent", "computation", "syntax", "FunctionDecl", "function",
			"Ident", "Parameters", "Parameters", "requires", "Expr", "ensures", "Expr", "Block", "Parameters",
			"Variable", "Variable", "syntax", "Those", "variables", "declared", "before", "are", "referred", "to", "as",
			"the", "parameters", "whilst", "those", "declared", "afterwards", "are", "referred", "to", "as", "the",
			"returns", "There", "are", "two", "kinds", "of", "optional", "clause", "which", "follow", "itemize",
			"Requires", "clause", "s", "These", "define", "constraints", "on", "the", "permissible", "values", "of",
			"the", "parameters", "on", "entry", "to", "the", "function", "and", "are", "often", "collectively",
			"referred", "to", "as", "the", "precondition", "These", "expressions", "may", "refer", "to", "any",
			"declared", "parameters", "Multiple", "clauses", "may", "be", "given", "and", "these", "are", "taken",
			"together", "as", "a", "conjunction", "The", "convention", "is", "to", "specify", "the", "requires",
			"clause", "s", "before", "any", "ensures", "clause", "s", "Ensures", "clause", "s", "These", "define",
			"constraints", "on", "the", "permissible", "values", "of", "the", "function", "s", "return", "value", "and",
			"are", "often", "collectively", "referred", "to", "as", "the", "postcondition", "These", "expressions",
			"may", "refer", "to", "any", "declared", "parameters", "or", "returns", "Multiple", "clauses", "may", "be",
			"given", "and", "these", "are", "taken", "together", "as", "a", "conjunction", "The", "convention", "is",
			"to", "specify", "ensures", "clause", "s", "after", "requires", "clause", "s", "itemize", "Examples", "The",
			"following", "function", "declaration", "provides", "a", "small", "example", "to", "illustrate", "examples",
			"ch3", "eg", "5", "whiley", "This", "defines", "the", "specification", "and", "implementation", "of", "the",
			"well", "known", "max", "function", "which", "returns", "the", "largest", "of", "its", "parameters", "This",
			"does", "not", "enforce", "any", "preconditions", "on", "its", "parameters", "Method", "Declarations", "c",
			"source", "files", "method", "decl", "A", "method", "declaration", "defines", "a", "method", "within", "a",
			"Whiley", "source", "file", "Methods", "are", "impure", "and", "may", "have", "side", "effects", "Thus",
			"they", "cannot", "be", "used", "within", "specifications", "i", "e", "in", "type", "invariants", "loop",
			"invariants", "and", "function", "method", "preconditions", "or", "postconditions", "However", "unlike",
			"functions", "methods", "may", "call", "other", "functions", "and", "or", "methods", "including", "native",
			"methods", "They", "may", "also", "explicitly", "allocate", "memory", "on", "the", "heap", "and", "or",
			"instigate", "concurrent", "computation", "syntax", "MethodDecl", "method", "LifetimeParameters", "Ident",
			"Parameters", "Parameters", "requires", "Expr", "ensures", "Expr", "Block", "LifetimeParameters", "Ident",
			"Ident", "syntax", "Those", "variables", "declared", "before", "are", "referred", "to", "as", "the",
			"parameters", "whilst", "those", "declared", "afterwards", "are", "referred", "to", "as", "the", "returns",
			"The", "two", "optional", "clauses", "are", "defined", "identically", "as", "for", "function",
			"declarations", "c", "source", "files", "function", "decl", "Examples", "The", "following", "method",
			"declaration", "provides", "a", "small", "example", "to", "illustrate", "examples", "ch3", "eg", "6",
			"whiley", "Definite", "Un", "Assignment", "c", "definite", "assignment", "The", "Whiley", "programming",
			"language", "requires", "that", "variables", "are", "known", "at", "compile", "time", "to", "be",
			"definitely", "assigned", "i", "e", "that", "they", "are", "defined", "before", "used", "and", "similarly",
			"that", "final", "variables", "are", "definitely", "unassigned", "at", "the", "point", "of", "assignment",
			"i", "e", "that", "they", "are", "assigned", "at", "most", "once", "A", "conservative", "approach", "is",
			"taken", "to", "determining", "whether", "or", "not", "these", "requirements", "hold", "true", "This",
			"ensures", "the", "language", "can", "be", "compiled", "efficiently", "but", "also", "means", "that",
			"some", "provably", "safe", "programs", "are", "not", "valid", "Whiley", "programs", "In", "this",
			"chapter", "we", "specify", "the", "process", "by", "which", "definite", "assignment", "and",
			"unassignment", "are", "determined", "The", "mechanism", "underpinning", "this", "is", "a", "data", "flow",
			"analysis", "over", "the", "control", "flow", "graph", "of", "a", "function", "to", "determine", "the",
			"assignment", "status", "of", "all", "local", "variables", "Overview", "The", "following", "illustrates",
			"a", "simple", "function", "which", "will", "be", "rejected", "by", "the", "compiler", "because", "it",
			"cannot", "determine", "definite", "assignment", "for", "all", "variables", "The", "function", "is", "said",
			"to", "fail", "definite", "assignment", "lstlisting", "function", "f", "int", "x", "int", "r", "int", "y",
			"if", "x", "0", "y", "1", "return", "x", "y", "lstlisting", "In", "the", "above", "program", "variable",
			"y", "is", "not", "definitely", "assigned", "before", "its", "use", "in", "the", "return", "statement",
			"This", "is", "because", "there", "is", "an", "execution", "path", "through", "the", "function", "which",
			"reaches", "the", "return", "statement", "and", "on", "which", "variable", "y", "is", "not", "defined",
			"see", "Figure", "f", "c8", "cfg", "1", "In", "fact", "there", "are", "two", "possible", "execution",
			"paths", "through", "this", "function", "but", "variable", "y", "is", "only", "defined", "on", "one", "of",
			"them", "Observe", "that", "since", "it", "is", "a", "parameter", "variable", "x", "is", "automatically",
			"considered", "to", "have", "been", "defined", "on", "entry", "to", "the", "function", "In", "contrast",
			"the", "following", "illustrates", "a", "simple", "function", "which", "will", "be", "rejected", "by",
			"the", "compiler", "because", "it", "cannot", "determine", "a", "final", "variable", "is", "definitely",
			"unassigned", "at", "the", "point", "of", "assignment", "lstlisting", "function", "g", "int", "x", "int",
			"r", "final", "int", "y", "0", "if", "x", "0", "y", "1", "return", "y", "lstlisting", "In", "the", "above",
			"program", "the", "final", "variable", "y", "is", "not", "definitely", "unassigned", "at", "the",
			"assignment", "on", "line", "5", "In", "other", "words", "there", "is", "an", "execution", "path",
			"through", "the", "function", "on", "which", "variable", "y", "is", "assigned", "more", "than", "once",
			"Such", "a", "path", "violates", "the", "intention", "of", "the", "final", "modifier", "which", "dictates",
			"that", "a", "variable", "should", "be", "assigned", "at", "most", "once", "figure", "t", "tikzpicture",
			"graynode", "style", "rectangle", "draw", "gray", "100", "fill", "gray", "20", "5", "very", "thick",
			"minimum", "size", "5mm", "minimum", "height", "1cm", "minimum", "width", "4cm", "rounded", "corners", "0",
			"25cm", "graynode", "l1", "at", "0", "4cm", "x", "0", "at", "1", "3", "25", "at", "1", "3", "25",
			"graynode", "l2", "at", "2", "5cm", "2cm", "y", "1", "graynode", "l3", "at", "0", "0", "return", "x", "y",
			"thick", "l1", "0", "5", "0", "5", "0", "5", "3", "2", "5", "3", "l2", "thick", "l2", "2", "5", "1", "0",
			"5", "1", "0", "5", "0", "5", "ultra", "thick", "0", "5", "3", "5", "0", "5", "0", "5", "tikzpicture",
			"Control", "Flow", "Graph", "for", "function", "f", "On", "the", "bold", "path", "y", "is", "undefined",
			"f", "c8", "cfg", "1", "figure", "Loops", "The", "treatment", "of", "loops", "with", "respect", "to",
			"definite", "un", "assignment", "warrants", "special", "attention", "Recall", "the", "mechanism", "for",
			"determining", "definite", "un", "assignment", "is", "conservative", "In", "the", "context", "of", "loops",
			"it", "simply", "assumes", "every", "loop", "can", "be", "executed", "zero", "or", "more", "times", "i",
			"e", "even", "if", "this", "is", "not", "correct", "From", "the", "perspective", "of", "definite",
			"assignment", "this", "implies", "that", "a", "variable", "assignment", "within", "a", "loop", "may", "not",
			"occur", "From", "the", "perspective", "of", "definite", "unassignment", "this", "implies", "that", "a",
			"variable", "assignment", "within", "a", "loop", "may", "occur", "The", "following", "illustrates",
			"lstlisting", "function", "f", "int", "x", "int", "int", "y", "while", "x", "0", "y", "1", "x", "x", "1",
			"return", "x", "y", "lstlisting", "The", "above", "function", "fails", "definite", "assignment", "because",
			"variable", "y", "is", "not", "defined", "when", "zero", "iterations", "of", "the", "loop", "are",
			"executed", "e", "g", "when", "x", "0", "on", "entry", "In", "contrast", "the", "following", "illustrates",
			"a", "function", "which", "fails", "definite", "unassignment", "lstlisting", "function", "g", "int", "x",
			"int", "final", "int", "y", "0", "while", "x", "0", "y", "1", "x", "x", "1", "return", "x", "y",
			"lstlisting", "The", "above", "function", "fails", "definite", "unassignment", "because", "variable", "y",
			"is", "defined", "more", "than", "once", "when", "one", "or", "more", "iterations", "of", "the", "loop",
			"are", "executed", "e", "g", "when", "x", "0", "on", "entry", "To", "illustrate", "the", "conservative",
			"nature", "of", "definite", "assignment", "consider", "this", "variation", "lstlisting", "function", "ten",
			"int", "int", "x", "0", "int", "y", "while", "x", "10", "y", "1", "x", "x", "1", "return", "y",
			"lstlisting", "Here", "it", "can", "be", "shown", "that", "y", "1", "must", "hold", "when", "the", "return",
			"statement", "is", "reached", "Nevertheless", "this", "function", "fails", "definite", "assignment",
			"because", "of", "the", "assumption", "that", "the", "loop", "executes", "zero", "or", "more", "iterations",
			"Infeasible", "Paths", "Functions", "and", "methods", "may", "contain", "infeasible", "pathinfeasible",
			"paths", "which", "are", "valid", "execution", "paths", "that", "in", "practice", "cannot", "be",
			"executed", "The", "mechanism", "for", "checking", "definite", "un", "assignment", "assumes", "for",
			"simplicity", "that", "any", "valid", "path", "can", "be", "executed", "This", "means", "that", "some",
			"programs", "will", "fail", "definite", "assignment", "even", "though", "they", "can", "be", "shown", "as",
			"safe", "The", "following", "illustrates", "such", "a", "program", "lstlisting", "function", "abs", "int",
			"x", "int", "int", "y", "if", "x", "0", "y", "x", "if", "x", "0", "y", "x", "return", "y", "lstlisting",
			"This", "function", "contains", "four", "valid", "execution", "paths", "which", "can", "be", "denoted",
			"by", "ff", "tf", "ft", "tt", "where", "for", "example", "tf", "represents", "the", "path", "where", "the",
			"first", "condition", "evaluates", "to", "true", "and", "the", "second", "to", "false", "However", "it",
			"is", "easy", "to", "see", "that", "execution", "paths", "ff", "and", "tt", "are", "infeasible",
			"Furthermore", "that", "on", "the", "other", "two", "paths", "tf", "and", "ft", "variable", "y", "is",
			"definitely", "assigned", "at", "the", "return", "statement", "Despite", "this", "the", "above", "function",
			"fails", "definite", "assignment", "because", "the", "mechanism", "considers", "all", "valid", "paths",
			"whilst", "ignoring", "infeasible", "execution", "paths", "Partial", "Assignments", "A", "variable", "will",
			"never", "be", "considered", "definitely", "assigned", "after", "the", "application", "of", "one", "or",
			"more", "partial", "assignments", "In", "contrast", "a", "variable", "is", "no", "longer", "considered",
			"definitely", "unassigned", "in", "such", "case", "The", "following", "illustrates", "a", "program",
			"which", "fails", "definite", "assignment", "even", "though", "it", "can", "be", "shown", "as", "safe",
			"lstlisting", "type", "Point", "is", "int", "x", "int", "y", "function", "Point", "int", "x", "int", "y",
			"Point", "Point", "p", "p", "x", "x", "p", "y", "y", "return", "p", "lstlisting", "In", "the", "above",
			"program", "the", "variable", "p", "can", "be", "shown", "as", "definitely", "assigned", "at", "the",
			"return", "statement", "Nevertheless", "the", "conservative", "mechanism", "for", "checking", "definite",
			"assignment", "will", "reject", "this", "program", "because", "variable", "p", "is", "initialised", "via",
			"partial", "assignments", "Description", "Definite", "assignment", "is", "defined", "over", "the",
			"control", "flow", "graph", "of", "a", "code", "block", "such", "as", "a", "requires", "or", "ensures",
			"clause", "or", "the", "body", "of", "a", "function", "or", "method", "Appendix", "c", "cfg", "details",
			"the", "process", "for", "constructing", "a", "control", "flow", "graph", "from", "a", "block", "of",
			"code", "Definite", "assignment", "considers", "the", "set", "of", "all", "valid", "paths", "in", "a",
			"control", "flow", "graph", "A", "valid", "path", "is", "a", "path", "through", "the", "graph", "starting",
			"from", "its", "root", "Every", "vertex", "in", "the", "graph", "is", "associated", "with", "a", "set",
			"of", "variables", "which", "are", "defined", "at", "that", "vertex", "as", "well", "as", "those", "which",
			"are", "used", "at", "that", "vertex", "A", "variable", "is", "said", "to", "be", "definitely", "assigned",
			"on", "entry", "to", "a", "vertex", "if", "for", "every", "valid", "path", "which", "includes", "some",
			"ancestor", "vertex", "exists", "on", "which", "is", "defined", "Definitions", "and", "Uses", "A",
			"variable", "definition", "occurs", "at", "a", "vertex", "which", "contains", "a", "direct", "assignment",
			"recall", "c", "stmt", "assign", "or", "an", "initialisation", "of", "recall", "c", "stmts", "var", "decl",
			"one", "or", "more", "variables", "Assignments", "to", "fields", "array", "elements", "or", "dereferenced",
			"references", "are", "not", "direct", "and", "do", "not", "define", "variables", "A", "vertex", "may",
			"define", "multiple", "variables", "if", "it", "corresponds", "to", "a", "multiple", "assignment", "which",
			"directly", "assigns", "those", "variables", "Finally", "the", "parameters", "of", "a", "function",
			"method", "or", "invariant", "block", "are", "treated", "as", "being", "defined", "on", "entry", "A",
			"variable", "use", "occurs", "at", "a", "vertex", "which", "directly", "refers", "to", "that", "variable",
			"in", "some", "expression", "other", "than", "an", "LVal", "However", "referring", "to", "a", "variable",
			"indirectly", "through", "a", "dereference", "expression", "does", "not", "constitute", "a", "variable",
			"use", "Errors", "and", "Warnings", "When", "the", "Whiley", "compiler", "encounters", "an", "invalid",
			"program", "it", "will", "report", "an", "error", "In", "contrast", "when", "it", "encounters", "something",
			"undesirable", "in", "an", "otherwise", "valid", "program", "it", "may", "report", "a", "warning", "This",
			"chapters", "details", "the", "complete", "list", "of", "error", "messages", "and", "warnings", "which",
			"can", "be", "reported", "for", "a", "Whiley", "program", "Overview", "Parse", "Errors", "Declarations",
			"Declarations", "are", "top", "level", "entities", "in", "a", "source", "file", "and", "their", "syntax",
			"is", "defined", "in", "c", "source", "files", "Cyclic", "Constant", "Declaration", "E301", "A", "cyclic",
			"constant", "declaration", "occurs", "when", "a", "constant", "declaration", "refers", "to", "itself",
			"either", "directly", "or", "indirectly", "This", "is", "an", "error", "because", "constants", "must", "be",
			"evaluated", "at", "compile", "time", "Example", "The", "following", "illustrates", "several", "cyclic",
			"constant", "declarations", "lstlisting", "constant", "const1", "is", "1", "const1", "constant", "const2",
			"is", "1", "const3", "constant", "const3", "is", "1", "const2", "lstlisting", "Here", "all", "three",
			"constant", "declarations", "are", "cyclic", "The", "declaration", "for", "const1", "has", "a", "direct",
			"cycle", "because", "its", "definition", "refers", "to", "itself", "The", "declaration", "for", "const2",
			"has", "an", "indirect", "cycle", "because", "its", "definition", "refers", "to", "const3", "which", "in",
			"turn", "refers", "back", "to", "const2", "Reference", "Not", "Permitted", "in", "Function", "E302", "A",
			"reference", "not", "permitted", "in", "function", "error", "occurs", "when", "an", "attempt", "is", "made",
			"to", "declare", "or", "use", "a", "variable", "of", "reference", "type", "in", "a", "function", "as",
			"opposed", "to", "a", "method", "Functions", "in", "Whiley", "must", "be", "free", "from", "side", "effect",
			"i", "e", "they", "must", "be", "pure", "Thus", "the", "potential", "side", "effects", "made", "possible",
			"through", "the", "use", "of", "references", "is", "not", "permitted", "Example", "The", "following",
			"illustrates", "a", "very", "simple", "example", "lstlisting", "function", "f", "int", "x", "int", "r",
			"return", "x", "lstlisting", "Here", "function", "f", "accepts", "a", "parameter", "x", "of", "reference",
			"type", "int", "which", "is", "not", "permitted", "In", "this", "case", "the", "function", "does", "not",
			"in", "fact", "exhibit", "any", "side", "effects", "nevertheless", "the", "function", "will", "currently",
			"be", "rejected", "Reference", "Operation", "Not", "Permitted", "in", "Function", "E303", "A", "reference",
			"operation", "not", "permitted", "in", "function", "error", "occurs", "when", "an", "attempt", "is", "made",
			"to", "operate", "on", "a", "variable", "of", "reference", "type", "in", "a", "function", "as", "opposed",
			"to", "a", "method", "Functions", "in", "Whiley", "must", "be", "free", "from", "side", "effect", "i", "e",
			"they", "must", "be", "pure", "Thus", "the", "potential", "side", "effects", "made", "possible", "through",
			"the", "use", "of", "references", "is", "not", "permitted", "Example", "The", "following", "illustrates",
			"a", "very", "simple", "example", "lstlisting", "function", "f", "int", "x", "int", "r", "int", "y", "x",
			"return", "y", "lstlisting", "Here", "function", "f", "obtains", "a", "reference", "to", "local",
			"variable", "y", "and", "then", "immediately", "dereferences", "it", "neither", "of", "which", "is",
			"permitted", "In", "this", "case", "the", "function", "does", "not", "in", "fact", "exhibit", "any", "side",
			"effects", "nevertheless", "the", "function", "will", "currently", "be", "rejected", "Method", "Invocation",
			"Not", "Permitted", "In", "Function", "E304", "A", "method", "invocation", "not", "permitted", "in",
			"function", "error", "occurs", "when", "an", "attempt", "is", "made", "to", "call", "a", "method", "from",
			"a", "function", "as", "opposed", "to", "another", "method", "Functions", "in", "Whiley", "must", "be",
			"free", "from", "side", "effect", "i", "e", "they", "must", "be", "pure", "Thus", "the", "potential",
			"side", "effects", "made", "possible", "through", "the", "method", "call", "are", "not", "permitted",
			"Example", "The", "following", "illustrates", "a", "very", "simple", "example", "lstlisting", "method", "g",
			"int", "x", "int", "y", "return", "x", "function", "f", "int", "x", "int", "r", "return", "g", "x",
			"lstlisting", "Here", "function", "f", "accepts", "a", "parameter", "x", "and", "passes", "it", "through",
			"a", "call", "to", "method", "g", "In", "this", "case", "method", "g", "does", "not", "in", "fact",
			"exhibit", "any", "side", "effects", "nevertheless", "the", "method", "call", "will", "be", "rejected",
			"Insufficient", "Return", "Values", "E305", "An", "insufficient", "return", "values", "error", "occurs",
			"when", "a", "return", "statement", "is", "encountered", "which", "does", "not", "provide", "as", "many",
			"return", "values", "as", "declared", "by", "the", "enclosing", "function", "or", "method", "Example",
			"The", "following", "illustrates", "two", "simple", "examples", "lstlisting", "method", "g", "int", "x",
			"int", "y", "int", "z", "return", "x", "1", "function", "f", "int", "x", "int", "return", "lstlisting",
			"Here", "method", "g", "is", "required", "to", "return", "two", "values", "but", "only", "one", "is",
			"actually", "being", "returned", "Likewise", "function", "f", "is", "required", "to", "return", "one",
			"value", "but", "none", "are", "actually", "being", "returned", "Too", "Many", "Return", "Values", "E306",
			"A", "too", "many", "return", "values", "error", "occurs", "when", "a", "return", "statement", "is",
			"encountered", "which", "provides", "more", "return", "values", "than", "declared", "by", "the",
			"enclosing", "function", "or", "method", "Example", "The", "following", "illustrates", "two", "simple",
			"examples", "lstlisting", "method", "g", "int", "x", "return", "x", "function", "f", "int", "x", "int",
			"return", "x", "x", "1", "lstlisting", "Here", "method", "g", "is", "required", "to", "return", "zero",
			"values", "but", "one", "is", "actually", "being", "returned", "Likewise", "function", "f", "is",
			"required", "to", "return", "one", "value", "but", "two", "are", "actually", "being", "returned", "Types",
			"c", "err", "types", "Subtype", "Error", "401", "A", "subtype", "error", "arises", "when", "an", "attempt",
			"is", "made", "to", "use", "an", "expression", "of", "type", "T", "in", "a", "position", "where", "an",
			"expression", "of", "type", "S", "is", "expected", "and", "T", "is", "not", "a", "subtype", "of", "S",
			"This", "is", "a", "common", "error", "precisely", "because", "it", "can", "occur", "in", "a", "large",
			"number", "of", "different", "situations", "Example", "The", "following", "illustrates", "an", "example",
			"lstlisting", "function", "f", "int", "x", "int", "r", "if", "x", "return", "0", "else", "return", "1",
			"lstlisting", "Here", "variable", "x", "has", "type", "int", "but", "is", "being", "used", "in", "a",
			"position", "i", "e", "as", "the", "condition", "of", "the", "if", "statement", "which", "expects", "a",
			"type", "bool", "Another", "example", "is", "as", "follows", "lstlisting", "function", "g", "int", "items",
			"int", "r", "return", "items", "lstlisting", "Here", "variable", "items", "has", "type", "int", "but", "is",
			"being", "used", "in", "a", "position", "i", "e", "as", "the", "return", "value", "which", "expects", "a",
			"type", "int", "Incomparable", "Operands", "402", "Record", "Type", "Required", "403", "Record", "Missing",
			"Field", "404", "Statements", "Statements", "are", "used", "frequently", "in", "a", "Whiley", "program",
			"and", "their", "syntax", "is", "defined", "elsewhere", "see", "c", "statements", "The", "error",
			"messages", "reported", "in", "this", "section", "are", "those", "related", "to", "specific", "statement",
			"forms", "Other", "more", "general", "errors", "can", "also", "be", "reported", "for", "a", "statement",
			"e", "g", "type", "errors", "c", "err", "types", "and", "are", "discussed", "elsewhere", "Invalid", "LVal",
			"E501", "An", "invalid", "lval", "error", "occurs", "when", "an", "invalid", "expression", "is", "used",
			"on", "the", "left", "hand", "side", "of", "an", "assignment", "Only", "expressions", "which", "are",
			"also", "lval", "s", "maybe", "used", "in", "such", "a", "situation", "see", "c", "stmt", "assign",
			"Example", "The", "following", "illustrates", "two", "invalid", "lval", "s", "lstlisting", "function", "f",
			"int", "x", "1", "x", "constant", "not", "valid", "lval", "x", "1", "x", "arithmetic", "expression", "not",
			"valid", "lvallstlisting", "The", "first", "assignment", "statement", "is", "invalid", "because", "one",
			"cannot", "assign", "to", "a", "constant", "The", "second", "is", "invalid", "because", "one", "cannot",
			"assign", "to", "an", "arithmetic", "expression", "Invalid", "Destructuring", "LVal", "E502", "An",
			"invalid", "destructuring", "lval", "error", "occurs", "when", "a", "destructuring", "assignment", "is",
			"used", "on", "the", "left", "hand", "side", "but", "the", "right", "hand", "side", "returns", "an",
			"incorrect", "number", "of", "values", "Example", "The", "following", "illustrates", "an", "invalid",
			"destructuring", "LVal", "lstlisting", "function", "f", "int", "x", "int", "y", "int", "return", "x", "y",
			"function", "g", "int", "x", "int", "y", "int", "x", "y", "f", "x", "y", "return", "x", "y", "lstlisting",
			"Here", "the", "invocation", "of", "f", "in", "g", "uses", "an", "invalid", "destructuring", "assignment",
			"because", "f", "returns", "one", "value", "but", "the", "assignment", "expects", "two", "Variable",
			"Already", "Defined", "E503", "A", "variable", "redefinition", "error", "occurs", "when", "a", "variable",
			"is", "declared", "with", "a", "name", "matching", "another", "variable", "already", "in", "scope", "This",
			"is", "an", "error", "because", "it", "is", "not", "permitted", "for", "one", "variable", "to", "shadow",
			"another", "Example", "The", "following", "illustrates", "an", "example", "of", "a", "variable",
			"redefinition", "lstlisting", "function", "sum", "int", "items", "int", "int", "i", "0", "int", "r", "0",
			"while", "i", "items", "int", "r", "items", "i", "i", "i", "1", "return", "r", "lstlisting", "Here", "the",
			"while", "loop", "attempts", "to", "declare", "a", "variable", "r", "but", "another", "variable", "r",
			"was", "already", "declared", "beforehand", "Unreachable", "Code", "E504", "An", "unreachable", "statement",
			"error", "arises", "in", "a", "function", "or", "method", "when", "no", "possible", "execution", "path",
			"could", "reach", "them", "Example", "The", "following", "illustrates", "some", "unreachable", "code",
			"lstlisting", "function", "abs", "int", "x", "int", "if", "x", "0", "return", "x", "else", "return", "x",
			"return", "0", "unreachable", "lstlisting", "Here", "the", "final", "return", "statement", "can", "never",
			"be", "reached", "by", "any", "execution", "path", "through", "the", "abs", "function", "This", "is",
			"considered", "an", "error", "because", "it", "indicates", "something", "undesirable", "which", "may",
			"not", "have", "been", "intended", "Branch", "Always", "Taken", "E506", "A", "branch", "always", "taken",
			"error", "occurs", "when", "a", "conditional", "branch", "is", "determine", "to", "always", "evaluate",
			"to", "either", "true", "or", "false", "Example", "The", "following", "illustrates", "a", "branch",
			"always", "taken", "lstlisting", "function", "f", "int", "x", "int", "if", "x", "is", "int", "return", "x",
			"else", "return", "1", "lstlisting", "Here", "the", "condition", "x", "is", "int", "always", "evaluates",
			"to", "true", "and", "hence", "the", "true", "branch", "of", "this", "conditional", "is", "always", "taken",
			"whilst", "the", "false", "branch", "is", "never", "taken", "Break", "Outside", "of", "Loop", "E507", "A",
			"break", "outside", "loop", "error", "occurs", "when", "a", "break", "statement", "is", "given", "which",
			"is", "not", "contained", "within", "one", "or", "more", "loops", "This", "is", "an", "error", "because",
			"the", "break", "statement", "is", "used", "specifically", "to", "exit", "a", "loop", "early", "and",
			"must", "be", "contained", "within", "the", "loop", "to", "be", "exited", "Example", "The", "following",
			"illustrates", "a", "break", "outside", "of", "a", "loop", "lstlisting", "function", "f", "int", "x", "int",
			"break", "return", "x", "lstlisting", "Here", "the", "break", "statement", "is", "meaningless", "as", "it",
			"is", "not", "associated", "with", "a", "loop", "Duplicate", "Default", "Label", "E508", "A", "duplicate",
			"default", "label", "error", "occurs", "when", "a", "switch", "statement", "includes", "more", "than",
			"one", "default", "label", "This", "is", "an", "error", "because", "at", "most", "one", "default", "is",
			"permitted", "Example", "The", "following", "illustrates", "an", "example", "of", "a", "duplicate",
			"default", "label", "lstlisting", "function", "f", "int", "x", "switch", "x", "case", "0", "return", "0",
			"default", "return", "1", "default", "return", "2", "lstlisting", "Here", "the", "switch", "statement",
			"has", "two", "default", "labels", "This", "must", "be", "an", "error", "as", "otherwise", "it", "would",
			"be", "ambiguous", "as", "to", "which", "executed", "Duplicate", "Case", "Label", "E509", "A", "duplicate",
			"case", "label", "error", "occurs", "when", "a", "switch", "statement", "includes", "more", "than", "one",
			"case", "label", "matching", "the", "same", "value", "This", "is", "an", "error", "because", "at", "most",
			"one", "case", "matching", "a", "given", "value", "is", "permitted", "Example", "The", "following",
			"illustrates", "an", "example", "of", "a", "duplicate", "case", "label", "lstlisting", "function", "f",
			"int", "x", "switch", "x", "case", "0", "return", "0", "case", "0", "1", "return", "1", "default", "return",
			"2", "lstlisting", "Here", "the", "switch", "statement", "has", "two", "case", "labels", "both", "of",
			"which", "match", "the", "value", "0", "This", "must", "be", "an", "error", "as", "otherwise", "it",
			"would", "be", "ambiguous", "as", "to", "which", "executed", "Expressions", "Expressions", "typically",
			"form", "the", "bulk", "of", "a", "Whiley", "program", "and", "their", "syntax", "is", "defined",
			"elsewhere", "see", "c", "expressions", "The", "error", "messages", "reported", "in", "this", "section",
			"are", "those", "related", "to", "specific", "expression", "forms", "More", "general", "errors", "can",
			"also", "be", "reported", "for", "an", "expression", "such", "as", "type", "errors", "see", "c", "err",
			"types", "Variable", "Possibly", "Uninitialised", "E601", "c", "err", "var", "uninitialised", "A",
			"variable", "possibly", "uninitialised", "error", "occurs", "when", "a", "variable", "may", "be", "used",
			"without", "being", "defined", "That", "is", "when", "a", "simple", "path", "exists", "through", "the",
			"control", "flow", "graph", "of", "a", "function", "or", "method", "from", "that", "variable", "s",
			"declaration", "to", "a", "use", "which", "contains", "no", "definition", "for", "that", "variable", "This",
			"error", "is", "reported", "as", "part", "of", "the", "definite", "assignment", "checking", "performed",
			"during", "compilation", "see", "c", "definite", "assignment", "Example", "The", "following", "illustrates",
			"a", "variable", "which", "is", "possibly", "uninitialised", "lstlisting", "function", "f", "int", "x",
			"int", "int", "y", "return", "x", "y", "lstlisting", "Here", "variable", "y", "is", "definitely",
			"uninitialised", "in", "the", "expression", "x", "y", "For", "more", "examples", "of", "variables", "which",
			"are", "possibly", "uninitialised", "see", "c", "definite", "assignment", "Unknown", "Variable", "E602",
			"An", "unknown", "variable", "error", "occurs", "when", "an", "attempt", "is", "made", "to", "access", "a",
			"variable", "which", "has", "not", "been", "declared", "in", "the", "current", "scope", "All", "variables",
			"must", "be", "declared", "before", "they", "can", "be", "used", "Example", "The", "following",
			"illustrates", "an", "unknown", "variable", "lstlisting", "function", "f", "int", "x", "int", "return", "x",
			"y", "lstlisting", "Here", "the", "return", "statements", "refers", "to", "an", "unknown", "variable", "y",
			"In", "contrast", "the", "reference", "to", "variable", "x", "is", "valid", "because", "x", "has", "been",
			"declared", "within", "scope", "Unknown", "Function", "or", "Method", "E603", "An", "unknown", "function",
			"or", "method", "error", "occurs", "when", "an", "attempt", "is", "made", "to", "access", "a", "function",
			"or", "method", "which", "is", "not", "visible", "in", "the", "current", "scope", "Functions", "and",
			"methods", "which", "are", "not", "declared", "in", "the", "same", "file", "as", "the", "invocation", "can",
			"be", "brought", "into", "the", "current", "scope", "using", "import", "statements", "Example", "The",
			"following", "illustrates", "an", "invocation", "of", "an", "unknown", "function", "or", "method",
			"lstlisting", "function", "f", "int", "x", "int", "return", "g", "x", "lstlisting", "Here", "function", "g",
			"is", "not", "defined", "in", "the", "current", "source", "file", "and", "has", "not", "been", "brought",
			"into", "scope", "through", "an", "import", "statement", "Ambiguous", "Coercion", "E604", "An", "ambiguous",
			"coercion", "error", "occurs", "when", "the", "target", "of", "a", "cast", "expression", "is", "uncertain",
			"That", "is", "when", "attempting", "to", "cast", "a", "value", "to", "a", "given", "type", "T", "but",
			"there", "is", "more", "than", "one", "way", "this", "can", "be", "achieved", "This", "error", "is",
			"reported", "as", "part", "of", "the", "coercion", "check", "performed", "during", "compilation", "Example",
			"The", "following", "illustrates", "an", "ambiguous", "coercion", "lstlisting", "type", "Ambiguous", "is",
			"int", "f1", "real", "f2", "real", "f1", "int", "f2", "function", "f", "int", "x", "int", "y", "Ambiguous",
			"return", "Ammbiguous", "f1", "x", "f2", "y", "lstlisting", "The", "cast", "is", "ambiguous", "here",
			"because", "it", "s", "unclear", "whether", "for", "example", "f1", "1", "f2", "2", "should", "become",
			"f1", "1", "0", "f2", "2", "or", "f1", "1", "f2", "2", "0", "Expressions", "c", "expressions", "The",
			"majority", "of", "work", "performed", "by", "a", "Whiley", "program", "is", "through", "the", "execution",
			"of", "expression", "Every", "expression", "produces", "a", "value", "and", "may", "have", "additional",
			"side", "effects", "Evaluation", "Order", "The", "operands", "for", "operators", "in", "Whiley", "are",
			"evaluated", "in", "a", "specific", "left", "to", "right", "evaluation", "order", "This", "always",
			"respects", "parentheses", "and", "operator", "precedence", "Furthermore", "aside", "from", "the", "short",
			"circuiting", "operators", "c", "expr", "logical", "connectives", "operands", "are", "always", "fully",
			"evaluated", "before", "any", "part", "of", "the", "operation", "is", "performed", "Operator", "Precedence",
			"To", "determine", "the", "evaluation", "order", "for", "mixed", "operator", "expressions", "without",
			"explicit", "parenthesis", "a", "fixed", "operator", "precedence", "is", "used", "This", "is", "first",
			"determined", "by", "operator", "class", "enumerate", "Unary", "Expressions", "This", "operator", "class",
			"represents", "operators", "which", "take", "exactly", "one", "operand", "This", "class", "takes",
			"highest", "precedence", "and", "includes", "operators", "such", "as", "arithmetic", "negation", "c",
			"expr", "negation", "and", "logical", "not", "c", "expr", "logical", "not", "Binary", "Infix",
			"Expressions", "This", "operator", "class", "represents", "operators", "which", "accept", "two", "operands",
			"with", "an", "infix", "syntax", "This", "class", "includes", "the", "usual", "range", "of", "common",
			"binary", "operators", "such", "as", "arithmetic", "operators", "c", "expr", "additive", "c", "expr",
			"multiplicative", "logical", "connectives", "c", "expr", "logical", "connectives", "etc", "Binary",
			"Mixfix", "Expressions", "This", "operator", "class", "represents", "operators", "which", "accept", "two",
			"operands", "but", "which", "are", "non", "infix", "operators", "and", "hence", "precedence", "is", "not",
			"ambiguous", "This", "class", "includes", "the", "array", "access", "c", "expr", "array", "access", "and",
			"field", "access", "operator", "c", "expr", "access", "N", "Ary", "Expressions", "This", "operator",
			"class", "represents", "operators", "which", "accept", "an", "arbitrary", "number", "of", "operands",
			"This", "class", "includes", "array", "constructors", "c", "expr", "array", "initialiser", "record",
			"constructors", "c", "expr", "record", "initialiser", "etc", "enumerate", "Within", "the", "class", "of",
			"binary", "infix", "expressions", "an", "explicit", "precedence", "rank", "is", "given", "for", "each",
			"operator", "syntax", "tabularcl", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "tabular", "syntax",
			"Lower", "ranked", "operators", "bind", "more", "tightly", "i", "e", "take", "higher", "precedence", "than",
			"higher", "ranked", "operators", "Unit", "Expressions", "c", "expr", "unit", "An", "expression", "returns",
			"exactly", "one", "value", "There", "is", "a", "large", "range", "of", "possible", "unit", "expressions",
			"including", "comparators", "arithmetic", "operators", "logical", "operators", "etc", "syntax", "Expr",
			"ArithmeticExpr", "BitwiseExpr", "CastExpr", "EqualityExpr", "InvokeExpr", "LambdaExpr", "LogicalExpr",
			"ArrayExpr", "RecordExpr", "ReferenceExpr", "TermExpr", "syntax", "Arithmetic", "Expressions", "c", "expr",
			"arithmetic", "Arithmetic", "expressions", "operate", "on", "values", "of", "numeric", "type", "currently",
			"just", "int", "syntax", "ArithmeticExpr", "ArithmeticNegationExpr", "ArithmeticRelationalExpr",
			"ArithmeticAdditiveExpr", "ArithmeticMultiplicativeExpr", "syntax", "Negation", "Expressions", "c", "expr",
			"negation", "A", "negation", "expression", "accepts", "one", "argument", "of", "numeric", "type", "and",
			"produces", "a", "result", "of", "matching", "type", "Specifically", "the", "negation", "operator",
			"mathematically", "negates", "the", "given", "value", "which", "is", "always", "equivalent", "to",
			"subtracting", "the", "operand", "from", "zero", "syntax", "ArithmeticNegationExpr", "Expr", "syntax",
			"Example", "The", "following", "illustrates", "the", "negation", "operator", "examples", "ch6", "eg", "13",
			"whiley", "Relational", "Expressions", "c", "expr", "relational", "Relational", "expressions", "are",
			"either", "strict", "where", "only", "inequality", "is", "tested", "or", "non", "strict", "where", "both",
			"equality", "and", "inequality", "are", "tested", "The", "less", "than", "comparator", "and", "greater",
			"than", "comparator", "are", "strict", "Conversely", "the", "less", "than", "or", "equal", "comparator",
			"and", "greater", "than", "or", "equal", "comparator", "are", "non", "strict", "syntax",
			"ArithmeticRelationalExpr", "Expr", "Expr", "Expr", "Expr", "Expr", "Expr", "Expr", "Expr", "syntax",
			"Example", "The", "following", "example", "illustrates", "the", "strict", "inequality", "comparators",
			"examples", "ch6", "eg", "5", "whiley", "This", "function", "compares", "two", "integer", "arguments",
			"and", "returns", "the", "sign", "of", "their", "comparison", "The", "strict", "inequality", "comparators",
			"are", "used", "so", "the", "case", "where", "x", "y", "can", "be", "distinguished", "Additive",
			"Expressions", "c", "expr", "additive", "An", "additive", "expression", "accepts", "two", "arguments", "of",
			"type", "int", "and", "produces", "a", "result", "of", "the", "same", "type", "The", "addition", "operator",
			"adds", "both", "arguments", "together", "whilst", "the", "subtraction", "operator", "subtracts", "its",
			"right", "argument", "from", "its", "left", "argument", "syntax", "ArithmeticAdditiveExpr", "Expr", "Expr",
			"syntax", "Example", "The", "following", "illustrates", "the", "additive", "operators", "examples", "ch6",
			"eg", "11", "whiley", "This", "function", "simply", "computes", "the", "difference", "between", "its",
			"two", "arguments", "using", "the", "subtraction", "operator", "Multiplicative", "Expressions", "c", "expr",
			"multiplicative", "A", "multiplicative", "expression", "accepts", "two", "arguments", "of", "type", "int",
			"and", "produces", "a", "result", "of", "the", "same", "type", "The", "multiplication", "operator",
			"multiplies", "both", "arguments", "together", "whilst", "the", "division", "operator", "divides", "its",
			"left", "argument", "by", "its", "right", "argument", "Finally", "the", "remainder", "operator", "returns",
			"the", "remainder", "of", "its", "operands", "from", "an", "implied", "division", "syntax",
			"ArithmeticMultiplicativeExpr", "Expr", "Expr", "syntax", "Example", "The", "following", "illustrates",
			"the", "remainder", "operator", "examples", "ch6", "eg", "12", "whiley", "This", "function", "accepts", "a",
			"non", "negative", "integer", "and", "uses", "this", "to", "index", "into", "an", "array", "To", "ensure",
			"the", "array", "access", "is", "within", "bounds", "the", "remainder", "operator", "is", "used",
			"Furthermore", "the", "function", "requires", "the", "array", "is", "non", "empty", "to", "prevent", "a",
			"fault", "with", "the", "remainder", "operator", "Notes", "For", "division", "the", "right", "operator",
			"must", "be", "non", "zero", "otherwise", "a", "fault", "is", "raised", "and", "likewise", "for",
			"remainder", "For", "integer", "division", "the", "result", "is", "rounded", "towards", "zero", "For", "a",
			"remainder", "operation", "the", "result", "may", "be", "negative", "e", "g", "4", "Array", "Expressions",
			"c", "expr", "array", "Array", "expressions", "operate", "on", "values", "of", "array", "type", "e", "g",
			"int", "boolbyte", "etc", "syntax", "ArrayExpr", "ArrayLengthExpr", "ArrayAccessExpr", "ArrayGeneratorExpr",
			"ArrayInitialiserExpr", "syntax", "Length", "Expressions", "c", "expr", "length", "The", "lengthof",
			"operator", "accepts", "a", "value", "of", "array", "type", "and", "produces", "a", "value", "of", "int",
			"type", "which", "equals", "the", "number", "of", "elements", "in", "the", "array", "syntax",
			"ArrayLengthExpr", "Expr", "syntax", "Example", "The", "following", "example", "illustrates", "the",
			"lengthof", "operator", "examples", "ch6", "eg", "19", "whiley", "The", "above", "function", "iterates",
			"through", "all", "elements", "in", "an", "array", "looking", "for", "the", "first", "which", "is", "above",
			"a", "given", "item", "The", "length", "operator", "is", "used", "to", "ensure", "this", "iteration",
			"remains", "within", "bounds", "Access", "Expressions", "c", "expr", "array", "access", "An", "array",
			"access", "expression", "accepts", "a", "array", "argument", "with", "one", "operand", "and", "produces",
			"a", "value", "of", "the", "array", "element", "type", "The", "index", "of", "operator", "returns", "the",
			"element", "at", "the", "given", "operand", "position", "in", "the", "array", "syntax", "ArrayAccessExpr",
			"Expr", "Expr", "syntax", "Examples", "The", "following", "example", "illustrates", "the", "array",
			"access", "operator", "examples", "ch6", "eg", "20", "whiley", "The", "above", "function", "determines",
			"whether", "a", "given", "array", "of", "integers", "is", "sorted", "from", "smallest", "to", "largest",
			"The", "array", "access", "operator", "is", "used", "to", "access", "successive", "elements", "in", "the",
			"array", "Generator", "Expressions", "c", "expr", "generator", "An", "array", "generator", "accepts", "two",
			"arguments", "and", "produces", "a", "value", "of", "array", "type", "The", "second", "argument", "must",
			"be", "of", "int", "type", "and", "the", "array", "produced", "contains", "exactly", "this", "many",
			"occurrences", "of", "the", "first", "argument", "syntax", "ArrayGeneratorExpr", "Expr", "Expr", "syntax",
			"Examples", "The", "following", "example", "illustrates", "an", "array", "generator", "examples", "ch6",
			"eg", "8", "whiley", "This", "function", "constructs", "a", "array", "by", "prepending", "a", "given",
			"element", "onto", "the", "front", "of", "a", "given", "array", "The", "array", "generator", "is", "used",
			"to", "construct", "the", "initial", "array", "of", "values", "whose", "size", "is", "one", "larger",
			"than", "the", "original", "array", "Array", "Initialiser", "c", "expr", "array", "initialiser", "An",
			"array", "initialiser", "accepts", "zero", "or", "more", "operands", "and", "produces", "a", "value", "of",
			"array", "type", "Array", "initialisers", "are", "used", "to", "construct", "arrays", "from", "their",
			"constituent", "elements", "syntax", "ArrayInitialiserExpr", "Expr", "Expr", "syntax", "Example", "The",
			"following", "example", "illustrates", "an", "array", "initialiser", "examples", "ch6", "eg", "21",
			"whiley", "The", "above", "function", "converts", "an", "integer", "value", "into", "its", "string",
			"representation", "An", "array", "initialiser", "is", "used", "to", "map", "integer", "values", "to",
			"their", "corresponding", "digits", "An", "empty", "array", "initialiser", "is", "also", "used", "to",
			"initialise", "the", "string", "Bitwise", "Expressions", "c", "expr", "bitwise", "Bitwise", "expressions",
			"operate", "on", "values", "of", "byte", "type", "syntax", "BitwiseExpr", "BitwiseComplementExpr",
			"BitwiseBinaryExpr", "BitwiseShiftExpr", "syntax", "Complement", "Expressions", "c", "expr", "bitwise",
			"complement", "The", "bitwise", "complement", "operator", "accepts", "an", "argument", "of", "byte", "type",
			"c", "types", "byte", "and", "produces", "a", "result", "of", "matching", "type", "The", "operator",
			"returns", "bitwise", "complement", "of", "the", "argument", "that", "is", "where", "the", "sign", "of",
			"each", "bit", "is", "reversed", "syntax", "BitwiseComplementExpr", "Expr", "syntax", "Example", "The",
			"following", "example", "illustrates", "the", "bitwise", "complement", "operator", "examples", "ch6", "eg",
			"15", "whiley", "Binary", "Expressions", "c", "expr", "bitwise", "binary", "A", "bitwise", "binary",
			"expression", "operates", "on", "values", "of", "byte", "type", "c", "types", "byte", "The", "bitwise",
			"AND", "operator", "performs", "a", "logical", "AND", "between", "the", "respective", "bits", "of", "each",
			"operand", "and", "produces", "a", "byte", "The", "bitwise", "OR", "operator", "performs", "a", "logical",
			"OR", "between", "the", "respective", "bits", "of", "each", "operand", "and", "produces", "a", "byte",
			"The", "bitwise", "exclusive", "OR", "operator", "performs", "a", "logical", "exclusive", "OR", "between",
			"the", "respective", "bits", "of", "each", "operand", "and", "produces", "a", "byte", "syntax",
			"BitwiseBinaryExpr", "Expr", "Expr", "syntax", "Example", "The", "following", "example", "illustrates",
			"the", "bitwise", "OR", "operator", "firstline", "3", "examples", "ch6", "eg", "3b", "whiley", "These",
			"functions", "provide", "mechanisms", "for", "manipulating", "a", "byte", "of", "flags", "as", "determined",
			"by", "the", "constant", "identifiers", "The", "bitwise", "OR", "operator", "is", "used", "to", "ensure",
			"a", "given", "bit", "is", "set", "whilst", "the", "bitwise", "AND", "operator", "is", "used", "to",
			"check", "whether", "one", "is", "set", "or", "not", "This", "example", "also", "illustrates", "the",
			"left", "shift", "operator", "c", "expr", "shift", "Shift", "Expressions", "c", "expr", "shift", "A",
			"bitwise", "shift", "expression", "accepts", "an", "argument", "of", "byte", "type", "left", "and", "one",
			"of", "int", "type", "right", "and", "produces", "a", "value", "of", "byte", "type", "The", "left", "shift",
			"operator", "shifts", "the", "bits", "of", "a", "byte", "in", "an", "upwards", "direction", "such", "that",
			"the", "most", "significant", "bit", "is", "discarded", "and", "the", "least", "significant", "bit",
			"assigned", "0", "The", "right", "shift", "operator", "shifts", "bits", "in", "a", "downwards", "direction",
			"such", "that", "the", "least", "significant", "bit", "is", "discarded", "and", "the", "most",
			"significant", "bit", "assigned", "0", "syntax", "BitwiseShiftExpr", "Expr", "Expr", "syntax", "Examples",
			"The", "following", "illustrates", "the", "left", "shift", "operator", "firstline", "3", "examples", "ch6",
			"eg", "10", "whiley", "This", "function", "accepts", "an", "integer", "between", "0", "and", "255", "and",
			"converts", "this", "into", "an", "appropriate", "bit", "representation", "The", "left", "shift",
			"operator", "is", "used", "to", "maintain", "an", "internal", "mask", "for", "the", "bit", "currently",
			"being", "initialised", "Cast", "Expressions", "c", "expr", "cast", "A", "cast", "operator", "accepts", "a",
			"value", "of", "one", "type", "and", "returns", "a", "value", "of", "a", "different", "but", "equivalent",
			"type", "and", "this", "may", "result", "in", "a", "change", "of", "the", "underlying", "representation",
			"syntax", "CastExpr", "DefiniteType", "Expr", "syntax", "Example", "The", "following", "illustrates", "a",
			"cast", "operator", "being", "used", "firstline", "3", "examples", "ch6", "eg", "16", "whiley", "This",
			"function", "converts", "a", "record", "containing", "three", "int", "fields", "into", "one", "containing",
			"two", "int", "fields", "This", "requires", "that", "each", "field", "in", "the", "latter", "is", "a",
			"valid", "field", "in", "the", "former", "Equality", "Expressions", "c", "expr", "equality", "The",
			"equality", "comparator", "tests", "whether", "two", "values", "are", "equal", "Likewise", "the",
			"inequality", "comparator", "tests", "whether", "two", "values", "are", "not", "equal", "syntax",
			"EqualityExpr", "Expr", "Expr", "Expr", "Expr", "syntax", "Example", "The", "following", "example",
			"illustrates", "an", "equality", "expression", "examples", "ch6", "eg", "4", "whiley", "This", "function",
			"checks", "whether", "a", "given", "integer", "is", "contained", "in", "an", "array", "of", "integers",
			"This", "is", "done", "by", "iterating", "each", "element", "of", "the", "array", "and", "comparing", "it",
			"against", "the", "given", "item", "Invoke", "Expressions", "c", "expr", "invoke", "A", "function", "or",
			"method", "invocation", "executes", "a", "named", "function", "or", "method", "declared", "in", "a",
			"given", "source", "file", "An", "indirect", "function", "or", "method", "invocation", "executes", "a",
			"function", "determined", "by", "a", "given", "expression", "An", "invocation", "passes", "arguments", "of",
			"appropriate", "number", "and", "type", "to", "the", "executed", "function", "or", "method", "An",
			"invocation", "may", "also", "return", "one", "or", "more", "values", "which", "can", "be", "subsequently",
			"used", "syntax", "InvokeExpr", "Name", "LifetimeArgsList", "ArgsList", "IndirectInvokeExpr", "Expr",
			"LifetimeArgsList", "ArgsList", "ArgsList", "Expr", "Expr", "LifetimeArgsList", "Lifetime", "Lifetime",
			"syntax", "Example", "The", "following", "example", "illustrates", "a", "function", "invocation",
			"examples", "ch6", "eg", "17", "whiley", "This", "example", "illustrates", "one", "function", "being",
			"called", "from", "another", "Both", "functions", "have", "the", "same", "name", "and", "are", "said", "to",
			"overload", "one", "another", "Function", "resolution", "identifies", "the", "appropriate", "function",
			"based", "on", "the", "number", "and", "type", "of", "arguments", "supplied", "Lambda", "Expressions", "c",
			"expr", "lambda", "A", "lambda", "expression", "creates", "an", "anonymous", "function", "or", "method",
			"which", "can", "accept", "zero", "or", "more", "arguments", "and", "whose", "return", "type", "is",
			"inferred", "from", "the", "body", "of", "the", "lambda", "syntax", "LambdaExpr", "ContextLifetimes",
			"LifetimeParameters", "Type", "Ident", "Type", "Ident", "Expr", "syntax", "Example", "The", "following",
			"example", "illustrates", "a", "lambda", "expression", "examples", "ch6", "eg", "25", "whiley", "This",
			"function", "illustrates", "the", "classical", "map", "function", "which", "applies", "a", "function", "to",
			"all", "elements", "of", "a", "collection", "In", "this", "case", "a", "lambda", "is", "used", "to",
			"create", "a", "function", "which", "adds", "a", "constant", "value", "to", "its", "argument", "This",
			"lambda", "is", "used", "to", "implement", "addAll", "in", "terms", "of", "map", "Logical", "Expressions",
			"c", "expr", "logical", "Logical", "expressions", "operate", "on", "values", "of", "bool", "type", "syntax",
			"LogicalExpr", "LogicalNotExpr", "LogicalBinaryExpr", "LogicalQuantExpr", "syntax", "Not", "Expressions",
			"c", "expr", "logical", "not", "The", "logical", "not", "operator", "accepts", "an", "argument", "of",
			"bool", "type", "and", "produces", "a", "value", "of", "bool", "The", "value", "returned", "is", "the",
			"logical", "opposite", "of", "the", "argument", "syntax", "LogicalNotExpr", "Expr", "syntax", "Example",
			"The", "following", "example", "illustrates", "the", "logical", "not", "operator", "examples", "ch6", "eg",
			"26", "whiley", "This", "function", "computes", "the", "maximum", "of", "two", "int", "values", "The",
			"expression", "a", "b", "is", "equivalent", "to", "a", "b", "and", "is", "used", "purely", "to",
			"illustrate", "the", "logical", "not", "operator", "Connective", "Expressions", "c", "expr", "logical",
			"connectives", "A", "logical", "connective", "operates", "on", "values", "of", "bool", "type", "c", "types",
			"bool", "to", "produce", "another", "bool", "value", "The", "if", "and", "only", "if", "iff", "operator",
			"returns", "true", "if", "either", "both", "operands", "are", "true", "or", "both", "are", "false", "The",
			"implication", "operator", "returns", "true", "if", "either", "the", "left", "operand", "is", "false", "or",
			"both", "operands", "are", "true", "The", "logical", "OR", "operator", "returns", "true", "if", "either",
			"operand", "is", "true", "whilst", "the", "logical", "AND", "operator", "returns", "true", "if", "both",
			"operands", "are", "true", "syntax", "LogicalBinaryExpr", "Expr", "Expr", "syntax", "Example", "The",
			"following", "examples", "illustrate", "some", "of", "the", "logical", "operators", "examples", "ch6", "eg",
			"2", "whiley", "The", "function", "implies", "implements", "the", "well", "known", "equivalence", "between",
			"implication", "and", "logical", "OR", "The", "function", "iff", "implements", "the", "well", "known",
			"equivalence", "between", "implication", "and", "iff", "Quantifier", "Expressions", "c", "expr",
			"quantifier", "A", "quantifier", "operates", "over", "an", "array", "of", "values", "and", "produces", "a",
			"value", "of", "bool", "type", "The", "universal", "quantifier", "all", "returns", "true", "if", "the",
			"given", "expression", "evaluates", "to", "true", "for", "every", "element", "in", "the", "array", "and",
			"false", "otherwise", "The", "existential", "quantifier", "some", "returns", "false", "if", "the", "given",
			"expression", "evaluates", "to", "false", "for", "every", "element", "in", "the", "array", "and", "true",
			"otherwise", "The", "inverted", "universal", "quantifier", "no", "returns", "true", "if", "the", "given",
			"expression", "evaluates", "to", "false", "for", "every", "element", "in", "the", "array", "and", "false",
			"otherwise", "syntax", "LogicalQuantExpr", "no", "some", "all", "Ident", "in", "Expr", "Ident", "in",
			"Expr", "Expr", "syntax", "Examples", "The", "following", "example", "illustrates", "the", "universal",
			"quantifier", "examples", "ch6", "eg", "18", "whiley", "Here", "the", "type", "natlist", "represents",
			"those", "integer", "arrays", "for", "which", "every", "element", "is", "a", "natural", "number", "i", "e",
			"greater", "or", "equal", "to", "zero", "Record", "Expressions", "c", "expr", "record", "Record",
			"expressions", "operate", "on", "values", "of", "record", "type", "e", "g", "int", "x", "int", "y", "etc",
			"Access", "Expressions", "c", "expr", "access", "The", "field", "access", "operator", "accepts", "a",
			"value", "of", "record", "type", "and", "returns", "the", "value", "held", "in", "a", "given", "field",
			"syntax", "FieldAccessExpr", "Expr", "Ident", "syntax", "Examples", "The", "following", "example",
			"illustrates", "a", "field", "access", "expression", "constructor", "examples", "ch6", "eg", "23", "whiley",
			"The", "above", "function", "computes", "the", "so", "called", "dot", "product", "of", "two", "vectors",
			"The", "field", "access", "operator", "is", "used", "to", "access", "the", "three", "fields", "of", "each",
			"vector", "Record", "Initialisers", "c", "expr", "record", "initialiser", "A", "record", "initialiser",
			"accepts", "one", "or", "more", "operands", "and", "produces", "a", "value", "of", "record", "type",
			"Record", "constructors", "are", "used", "to", "construct", "records", "from", "their", "constituent",
			"elements", "syntax", "RecordInitialiserExpr", "FieldArgsList", "FieldArgsList", "Ident", "Expr", "Ident",
			"Expr", "syntax", "Example", "The", "following", "example", "illustrates", "a", "record", "initialiser",
			"examples", "ch6", "eg", "22", "whiley", "The", "above", "function", "simply", "translates", "a", "Point",
			"from", "one", "position", "to", "another", "based", "on", "a", "shift", "in", "x", "and", "in", "y", "The",
			"record", "initialiser", "is", "used", "to", "construct", "the", "new", "Point", "Reference", "Expressions",
			"Reference", "expressions", "operate", "on", "values", "of", "reference", "type", "e", "g", "int", "New",
			"Expressions", "c", "expr", "new", "A", "new", "expression", "accepts", "an", "argument", "of", "any",
			"type", "and", "produces", "a", "reference", "to", "that", "type", "The", "new", "operator", "allocates",
			"sufficient", "space", "on", "the", "heap", "and", "initialises", "it", "with", "the", "given", "value",
			"It", "then", "returns", "a", "reference", "to", "this", "heap", "object", "syntax", "NewExpr", "new",
			"Expr", "Lifetime", "new", "Expr", "syntax", "Example", "The", "following", "example", "illustrates", "the",
			"new", "operator", "examples", "ch6", "eg", "24", "whiley", "This", "example", "illustrates", "an",
			"operation", "for", "adding", "an", "item", "onto", "the", "front", "of", "a", "classical", "linked",
			"list", "Here", "a", "LinkedList", "is", "either", "null", "or", "a", "reference", "to", "a", "node",
			"containing", "a", "next", "reference", "and", "data", "item", "The", "add", "operation", "simply",
			"allocates", "a", "new", "node", "and", "places", "it", "on", "the", "front", "of", "the", "list",
			"Dereference", "Expressions", "c", "expr", "dereference", "A", "dereference", "expression", "accepts", "an",
			"argument", "of", "reference", "type", "and", "returns", "a", "value", "or", "element", "of", "the",
			"reference", "s", "target", "type", "The", "dereference", "operator", "returns", "the", "value",
			"referenced", "by", "the", "argument", "The", "arrow", "operator", "returns", "a", "field", "of", "the",
			"value", "referenced", "by", "the", "argument", "syntax", "DereferenceExpr", "TermExpr", "Expr", "Ident",
			"syntax", "Example", "The", "following", "illustrates", "the", "dereference", "operator", "examples", "ch6",
			"eg", "14", "whiley", "This", "method", "traverses", "a", "linked", "list", "counting", "the", "number",
			"of", "links", "it", "contains", "The", "arrow", "operator", "is", "used", "to", "access", "the", "next",
			"link", "in", "the", "chain", "Notes", "The", "arrow", "operation", "e", "f", "is", "a", "short", "hand",
			"notation", "for", "e", "f", "and", "can", "be", "used", "when", "e", "has", "effective", "record", "type",
			"c", "types", "effective", "records", "Terminal", "Expressions", "c", "expr", "term", "A", "terminal",
			"expression", "is", "one", "which", "can", "terminate", "an", "expression", "tree", "though", "does", "not",
			"necessarily", "do", "so", "For", "example", "a", "numeric", "literal", "represents", "a", "terminal",
			"node", "in", "an", "expression", "tree", "syntax", "TermExpr", "Ident", "Literal", "Expr", "syntax",
			"Type", "Test", "Expressions", "c", "expr", "type", "tests", "syntax", "TypeTestExpr", "Expr", "is", "Type",
			"syntax", "abrupt", "termination", "name", "abrupt", "termination", "description", "A", "statement",
			"terminates", "abruptly", "if", "a", "subexpression", "causes", "an", "exception", "to", "be", "thrown",
			"This", "includes", "exceptions", "thrown", "and", "not", "caught", "by", "an", "invoked", "function", "or",
			"method", "assertion", "name", "assertion", "description", "An", "assertion", "statement", "is",
			"specified", "with", "the", "assert", "keyword", "and", "identifies", "a", "condition", "which", "must",
			"hold", "at", "that", "point", "for", "all", "possible", "executions", "access", "control", "name",
			"access", "control", "description", "Mechanisms", "for", "restricting", "the", "visibility", "of", "named",
			"declaration", "boolean", "expression", "name", "boolean", "expression", "description", "An", "expression",
			"which", "evaluates", "to", "a", "value", "of", "type", "bool", "block", "comment", "name", "block",
			"comment", "description", "A", "block", "comment", "begins", "with", "and", "continues", "until", "the",
			"end", "of", "comment", "marker", "control", "flow", "graph", "name", "control", "flow", "graph",
			"description", "A", "directed", "graph", "representation", "of", "a", "block", "of", "code", "e", "g", "a",
			"function", "or", "method", "body", "with", "which", "one", "can", "reason", "about", "the", "set", "of",
			"possible", "execution", "path", "contractive", "name", "contractive", "description", "A", "type", "is",
			"contractive", "if", "it", "does", "not", "describe", "an", "infinite", "series", "of", "self",
			"applications", "compile", "time", "name", "compile", "time", "description", "The", "point", "in", "time",
			"at", "which", "a", "given", "compilation", "group", "is", "compiled", "into", "binary", "form",
			"compilation", "group", "name", "compilation", "group", "description", "A", "group", "of", "one", "or",
			"more", "source", "files", "being", "compiled", "together", "compilation", "unit", "name", "compilation",
			"unit", "description", "A", "single", "unit", "of", "compilation", "In", "Whiley", "this", "includes",
			"source", "files", "and", "also", "binary", "wyil", "files", "constant", "declaration", "name", "constant",
			"declaration", "description", "A", "source", "level", "declaration", "which", "associates", "a", "name",
			"with", "a", "constant", "expression", "The", "full", "name", "of", "the", "declared", "entity", "is",
			"determined", "from", "the", "package", "and", "name", "of", "the", "enclosing", "source", "file",
			"default", "package", "name", "default", "package", "description", "The", "top", "level", "package",
			"which", "has", "no", "name", "and", "is");
}
